using Content.Client.UserInterface.Controls;
using Content.Shared._BRatbite.Genetics;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;
using System.Linq;
using static Robust.Client.UserInterface.Controls.BoxContainer;

namespace Content.Client._BRatbite.Genetics;

[GenerateTypedNameReferences]
public sealed partial class GeneticComputerWindow : FancyWindow
{
    [Dependency] private readonly IGameTiming _timing = default!;
    private TimeSpan _printCooldown;
    private int _selectedSequenceId = -1;
    private IList<Sequence> _sequences = new List<Sequence>();
    public int SelectedSequenceId
    {
        get => _selectedSequenceId;
        set
        {
            if (_selectedSequenceId != value)
            {
                _selectedSequenceId = value;
                PopulateDNAEditor();
            }
        }
    }
    // Colors for the buttons
    private Dictionary<NucleoBase, Color> _nucleoColors = new()
    {
        [NucleoBase.A] = new(0xff, 0x8c, 0x00),
        [NucleoBase.T] = new(0xff, 0x8c, 0x00),
        [NucleoBase.C] = new(0x44, 0x88, 0xff),
        [NucleoBase.G] = new(0x44, 0x88, 0xff),
        [NucleoBase.X] = new(0xaa, 0xaa, 0xaa),
    };

    public GeneticComputerWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
    }

    public void Populate(GeneticComputerScanInfoInterface state)
    {
        SubjectName.Text = state.SubjectName;
        SubjectStatus.Text = state.SubjectStatus;
        GeneticDamage.Text = state.GeneticDamage.ToString("P1");
        _printCooldown = state.PrintCooldown;
        PopulateSequencer(state.SequencerStatus);
        UpdateTimings();
    }

    private void PopulateSequencer(SequencerStatus sequencerStatus)
    {
        _sequences = sequencerStatus.Sequences;
        SelectedSequenceId = sequencerStatus.SelectedSequenceId;
        SequenceContainer.RemoveAllChildren();
        foreach (var seq in _sequences)
        {
            Button button = new();
            button.OnPressed += (_) =>
            {
                SelectedSequenceId = seq.Number;
                // TODO: fire event
            };
            button.Pressed = SelectedSequenceId == seq.Number;
            button.HorizontalExpand = true;
            button.Margin = new(0, 2, 0, 2);
            BoxContainer box = new();
            button.AddChild(box);
            Label id = new();
            id.Text = seq.Number.ToString();
            id.MinWidth = 24;
            Label info = new();
            info.Text = seq.Info;
            info.HorizontalExpand = true;
            Label activeInfo = new();
            activeInfo.Margin = new(10, 0, 0, 0);
            activeInfo.Modulate = seq.Activated ? new(0x32, 0xcd, 0x32) : new(0xaa, 0xaa, 0xaa);
            activeInfo.Text = Loc.GetString(seq.Activated ? "genetic-computer-activate" : "genetic-computer-inactive");
            box.AddChild(id);
            box.AddChild(info);
            box.AddChild(activeInfo);

            SequenceContainer.AddChild(button);
        }
    }

    private void PopulateDNAEditor()
    {
        DNAContainer.RemoveAllChildren();
        var selectedSequence = _sequences.FirstOrDefault(s => s.Number == _selectedSequenceId);
        if (selectedSequence is null) return;
        SelectedSequenceName.Text = selectedSequence.Info;
        SelectedSequenceNumber.Text = selectedSequence.Number.ToString();

        foreach (var chunk in selectedSequence.Dna.Chunk(4))
        {
            PanelContainer panel = new();
            panel.AddStyleClass("BorderedPanel");
            panel.Margin = new(0, 0, 0, 6);
            BoxContainer box = new();
            box.Orientation = LayoutOrientation.Vertical;
            box.Margin = new(4, 4, 4, 4);
            panel.AddChild(box);
            foreach (var pair in chunk)
            {
                BoxContainer pairContainer = new();
                pairContainer.Margin = new(0, 1, 0, 1);
                Button firstBase = new();
                firstBase.Text = pair.Item1.ToString();
                firstBase.MinWidth = 32;
                firstBase.Modulate = _nucleoColors[pair.Item1];
                Label separator = new();
                separator.Text = "-";
                Button secondBase = new();
                secondBase.Text = pair.Item2.ToString();
                secondBase.MinWidth = 32;
                secondBase.Modulate = _nucleoColors[pair.Item2];
                pairContainer.AddChild(firstBase);
                pairContainer.AddChild(separator);
                pairContainer.AddChild(secondBase);
                box.AddChild(pairContainer);
            }
            DNAContainer.AddChild(panel);
        }
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);
        UpdateTimings();
    }

    private void UpdateTimings()
    {
        var time = _printCooldown - _timing.CurTime;
        if (time.TotalSeconds <= 0)
            PrintCooldown.Text = "Ready";
        else
            PrintCooldown.Text = $"{Math.Ceiling(time.TotalSeconds):F0}s";
    }
}
